version: '3.8'
services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Chicago
    volumes:
      - /home/scott/docker/plex/config:/config
      - /mnt/media:/media
    restart: unless-stopped
