version: '3.8'

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/etc/suricata
      - ./logs:/var/log/suricata
      - ./rules:/var/lib/suricata/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: >
      suricata -c /etc/suricata/suricata.yaml -i ens18 --init-errors-fatal
    healthcheck:
      test: ["CMD", "pgrep", "suricata"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  suricata_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/scott/docker/suricata/logs

networks:
  default:
    external:
      name: host