services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'Rainbow Sunshine 123'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - './logs:/var/log/pihole'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    network_mode: "host"

