version: "3.9"

networks:
  media_net:
    driver: bridge

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/downloads/completed:/completed downloads
      - /mnt/media/downloads/intermediate:/intermediate downloads
      - /home/scott/docker/sabnzbd/config:/config
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - media_net

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/TV:/tv
      - /mnt/media/downloads/completed:/completed downloads
      - /home/scott/docker/sonarr/config:/config
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - media_net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/Movies:/movies
      - /mnt/media/downloads/completed:/completed downloads
      - /home/scott/docker/radarr/config:/config
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - media_net

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/media/Music:/music
      - /mnt/media/downloads/completed:/completed downloads
      - /home/scott/docker/lidarr/config:/config
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks:
      - media_net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/scott/docker/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media_net

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/scott/docker/overseerr/config:/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    networks:
      - media_net

  huntarr:
    image: ghcr.io/plexguide/huntarr:latest
    container_name: huntarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/scott/docker/huntarr/config:/config
    ports:
      - "9705:9705"
    restart: unless-stopped
    networks:
      - media_net
